config/routes.rb
Rails.application.routes.draw do
	root 'coffee_roasts#index'
  resources :coffee_roasts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cam.rb
class Cam < ApplicationRecord
end

app/models/coffee_roast.rb
class CoffeeRoast < ApplicationRecord
end

app/models/ff.rb
class Ff < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/sdfsd.rb
class Sdfsd < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffee_roasts_controller.rb
class CoffeeRoastsController < ApplicationController
  before_action :set_coffee_roast, only: [:show, :edit, :update, :destroy]

  # GET /coffee_roasts
  # GET /coffee_roasts.json
  def index
    @coffee_roasts = CoffeeRoast.all
  end

  # GET /coffee_roasts/1
  # GET /coffee_roasts/1.json
  def show
  end

  # GET /coffee_roasts/new
  def new
    @coffee_roast = CoffeeRoast.new
  end

  # GET /coffee_roasts/1/edit
  def edit
  end

  # POST /coffee_roasts
  # POST /coffee_roasts.json
  def create
    @coffee_roast = CoffeeRoast.new(coffee_roast_params)

  respond_to do |format|
    if @coffee_roast.save
      message = "The coffee roast '#{@coffee_roast.roast_name}' was just added."
      TwilioTextMessenger.new(message).call
      format.html { redirect_to @coffee_roast, notice: 'Coffee roast was successfully created.' }
      format.json { render :show, status: :created, location: @coffee_roast }
    else
      format.html { render :new }
      format.json { render json: @coffee_roast.errors, status: :unprocessable_entity }
    end
  end

  end

  # PATCH/PUT /coffee_roasts/1
  # PATCH/PUT /coffee_roasts/1.json
  def update
    respond_to do |format|
      if @coffee_roast.update(coffee_roast_params)
        format.html { redirect_to @coffee_roast, notice: 'Coffee roast was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffee_roast }
      else
        format.html { render :edit }
        format.json { render json: @coffee_roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_roasts/1
  # DELETE /coffee_roasts/1.json
  def destroy
    @coffee_roast.destroy
    respond_to do |format|
      format.html { redirect_to coffee_roasts_url, notice: 'Coffee roast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_roast
      @coffee_roast = CoffeeRoast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_roast_params
      params.require(:coffee_roast).permit(:roast_name, :roast_description)
    end
end

app/controllers/mm_controller.rb
class MmController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_roasts_helper.rb
module CoffeeRoastsHelper
end

app/helpers/mm_helper.rb
module MmHelper
end

app/helpers/sunk_helper.rb
module SunkHelper
end

app/views/coffee_roasts/_form.html.erb
<%= form_with(model: coffee_roast, local: true) do |form| %>
  <% if coffee_roast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee_roast.errors.count, "error") %> prohibited this coffee_roast from being saved:</h2>

      <ul>
      <% coffee_roast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :roast_name %>
    <%= form.text_field :roast_name %>
  </div>

  <div class="field">
    <%= form.label :roast_description %>
    <%= form.text_area :roast_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffee_roasts/edit.html.erb
<h1>Editing Coffee Roast</h1>

<%= render 'form', coffee_roast: @coffee_roast %>

<%= link_to 'Show', @coffee_roast %> |
<%= link_to 'Back', coffee_roasts_path %>

app/views/coffee_roasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffee Roasts</h1>

<table>
  <thead>
    <tr>
      <th>Roast name</th>
      <th>Roast description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffee_roasts.each do |coffee_roast| %>
      <tr>
        <td><%= coffee_roast.roast_name %></td>
        <td><%= coffee_roast.roast_description %></td>
        <td><%= link_to 'Show', coffee_roast %></td>
        <td><%= link_to 'Edit', edit_coffee_roast_path(coffee_roast) %></td>
        <td><%= link_to 'Destroy', coffee_roast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee Roast', new_coffee_roast_path %>

app/views/coffee_roasts/new.html.erb
<h1>New Coffee Roast</h1>

<%= render 'form', coffee_roast: @coffee_roast %>

<%= link_to 'Back', coffee_roasts_path %>

app/views/coffee_roasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roast name:</strong>
  <%= @coffee_roast.roast_name %>
</p>

<p>
  <strong>Roast description:</strong>
  <%= @coffee_roast.roast_description %>
</p>

<%= link_to 'Edit', edit_coffee_roast_path(@coffee_roast) %> |
<%= link_to 'Back', coffee_roasts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>